apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techchallenge-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20  # escala se uso > 70% da CPU
