# Esse arquivo é usado somente para fins de desenvolvimento local.
# Na pipeline do GitHub Actions, o segredo é criado dinamicamente.

apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-secret
type: Opaque
stringData:
  POSTGRES_USER: "techchallenge_root"
  POSTGRES_PASSWORD: "techchallenge123"
